"""Add hathifiles_timestamp column to item

Revision ID: c15f52a6ef8f
Revises: bbb334fc10e7
Create Date: 2025-10-15 15:01:17.096337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15f52a6ef8f'
down_revision: Union[str, None] = 'bbb334fc10e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('hathifiles_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'hathifiles_timestamp')
    # ### end Alembic commands ###
