name: Continuous integration
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize, edited]
permissions:
  contents: write
  pull-requests: write
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create .env file
        run: cat env.* > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
      - name: Install rclone
        run: sudo apt install -y rclone
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          cache: 'poetry'
      - name: Install poetry packages
        run: poetry install
      - name: setup pytest.ini
        run: mv .github/pytest.ini pytest.ini
      - name: Linting
        run: poetry run ruff check
      - name: Run tests
        env:
          CI: "true"
        run: poetry run pytest
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
      - name: Setup Shell Mock
        run: wget -P /opt/ https://github.com/boschresearch/shellmock/releases/download/0.9.1/shellmock.bash
      - run: ls /opt
      - name: Run tests
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          SHELLMOCK_PATH: /opt/shellmock.bash
          TERM: xterm
        run: bats ./bin/**/*_test.sh
  dependabot:
    name: 'Dependabot'
    needs: [test-python, test-bash]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        # Don't do this for the container-updates group
        if: ${{ steps.dependabot-metadata.outputs.dependency-group != 'container-updates' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
