name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true


jobs:
  build-production:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-production-digifeeds:
    needs: build-production
    name: Deploy to production - digifeeds
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/digifeeds/production/app-image.txt
    secrets: inherit

  deploy-production-hathifiles:
    needs: build-production
    name: Deploy to production - hathifiles
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/hathifiles/production/cli-image.txt
    secrets: inherit
